export class TicketDto {
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
  updatedBy?: string;
  flexBoolean0?: string;
  flexBoolean1?: string;
  flexBoolean2?: string;
  flexBoolean3?: string;
  flexBoolean4?: string;
  flexBoolean5?: string;
  flexBoolean6?: string;
  flexBoolean7?: string;
  flexBoolean8?: string;
  flexBoolean9?: string;
  flexFloat0?: string;
  flexFloat1?: string;
  flexFloat2?: string;
  flexFloat3?: string;
  flexFloat4?: string;
  flexFloat5?: string;
  flexFloat6?: string;
  flexFloat7?: string;
  flexFloat8?: string;
  flexFloat9?: string;
  flexInt0?: string;
  flexInt1?: string;
  flexInt2?: string;
  flexInt3?: string;
  flexInt4?: string;
  flexInt5?: string;
  flexInt6?: string;
  flexInt7?: string;
  flexInt8?: string;
  flexInt9?: string;
  flexString0?: string;
  flexString1?: string;
  flexString2?: string;
  flexString3?: string;
  flexString4?: string;
  flexString5?: string;
  flexString6?: string;
  flexString7?: string;
  flexString8?: string;
  flexString9?: string;
  flexString10?: string;
  flexString11?: string;
  flexString12?: string;
  flexString13?: string;
  flexString14?: string;
  flexString15?: string;
  flexString16?: string;
  flexString17?: string;
  flexString18?: string;
  flexString19?: string;
  flexString20?: string;
  flexBigint0?: string;
  flexBigint1?: string;
  flexBigint2?: string;
  flexBigint3?: string;
  flexBigint4?: string;
  flexBigint5?: string;
  flexBigint6?: string;
  flexBigint7?: string;
  flexBigint8?: string;
  flexBigint9?: string;
  orderId?: string;
  ticketDefRelId?: string;
  ticketId?: string;
  ticketTypeId?: string;

  static fromObject(object: any): TicketDto {
    const ticketDto: TicketDto = {};

    if (object) {
      ticketDto.createdBy = object.createdBy ?? undefined;
      ticketDto.createdAt = object.createdAt ?? undefined;
      ticketDto.updatedAt = object.updatedAt ?? undefined;
      ticketDto.updatedBy = object.updatedBy ?? undefined;
      ticketDto.flexBoolean0 = object.flexBoolean0 ?? undefined;
      ticketDto.flexBoolean1 = object.flexBoolean1 ?? undefined;
      ticketDto.flexBoolean2 = object.flexBoolean2 ?? undefined;
      ticketDto.flexBoolean3 = object.flexBoolean3 ?? undefined;
      ticketDto.flexBoolean4 = object.flexBoolean4 ?? undefined;
      ticketDto.flexBoolean5 = object.flexBoolean5 ?? undefined;
      ticketDto.flexBoolean6 = object.flexBoolean6 ?? undefined;
      ticketDto.flexBoolean7 = object.flexBoolean7 ?? undefined;
      ticketDto.flexBoolean8 = object.flexBoolean8 ?? undefined;
      ticketDto.flexBoolean9 = object.flexBoolean9 ?? undefined;
      ticketDto.flexFloat0 = object.flexFloat0 ?? undefined;
      ticketDto.flexFloat1 = object.flexFloat1 ?? undefined;
      ticketDto.flexFloat2 = object.flexFloat2 ?? undefined;
      ticketDto.flexFloat3 = object.flexFloat3 ?? undefined;
      ticketDto.flexFloat4 = object.flexFloat4 ?? undefined;
      ticketDto.flexFloat5 = object.flexFloat5 ?? undefined;
      ticketDto.flexFloat6 = object.flexFloat6 ?? undefined;
      ticketDto.flexFloat7 = object.flexFloat7 ?? undefined;
      ticketDto.flexFloat8 = object.flexFloat8 ?? undefined;
      ticketDto.flexFloat9 = object.flexFloat9 ?? undefined;
      ticketDto.flexInt0 = object.flexInt0 ?? undefined;
      ticketDto.flexInt1 = object.flexInt1 ?? undefined;
      ticketDto.flexInt2 = object.flexInt2 ?? undefined;
      ticketDto.flexInt3 = object.flexInt3 ?? undefined;
      ticketDto.flexInt4 = object.flexInt4 ?? undefined;
      ticketDto.flexInt5 = object.flexInt5 ?? undefined;
      ticketDto.flexInt6 = object.flexInt6 ?? undefined;
      ticketDto.flexInt7 = object.flexInt7 ?? undefined;
      ticketDto.flexInt8 = object.flexInt8 ?? undefined;
      ticketDto.flexInt9 = object.flexInt9 ?? undefined;
      ticketDto.flexString0 = object.flexString0 ?? undefined;
      ticketDto.flexString1 = object.flexString1 ?? undefined;
      ticketDto.flexString2 = object.flexString2 ?? undefined;
      ticketDto.flexString3 = object.flexString3 ?? undefined;
      ticketDto.flexString4 = object.flexString4 ?? undefined;
      ticketDto.flexString5 = object.flexString5 ?? undefined;
      ticketDto.flexString6 = object.flexString6 ?? undefined;
      ticketDto.flexString7 = object.flexString7 ?? undefined;
      ticketDto.flexString8 = object.flexString8 ?? undefined;
      ticketDto.flexString9 = object.flexString9 ?? undefined;
      ticketDto.flexString10 = object.flexString10 ?? undefined;
      ticketDto.flexString11 = object.flexString11 ?? undefined;
      ticketDto.flexString12 = object.flexString12 ?? undefined;
      ticketDto.flexString13 = object.flexString13 ?? undefined;
      ticketDto.flexString14 = object.flexString14 ?? undefined;
      ticketDto.flexString15 = object.flexString15 ?? undefined;
      ticketDto.flexString16 = object.flexString16 ?? undefined;
      ticketDto.flexString17 = object.flexString17 ?? undefined;
      ticketDto.flexString18 = object.flexString18 ?? undefined;
      ticketDto.flexString19 = object.flexString19 ?? undefined;
      ticketDto.flexString20 = object.flexString20 ?? undefined;
      ticketDto.flexBigint0 = object.flexBigint0 ?? undefined;
      ticketDto.flexBigint1 = object.flexBigint1 ?? undefined;
      ticketDto.flexBigint2 = object.flexBigint2 ?? undefined;
      ticketDto.flexBigint3 = object.flexBigint3 ?? undefined;
      ticketDto.flexBigint4 = object.flexBigint4 ?? undefined;
      ticketDto.flexBigint5 = object.flexBigint5 ?? undefined;
      ticketDto.flexBigint6 = object.flexBigint6 ?? undefined;
      ticketDto.flexBigint7 = object.flexBigint7 ?? undefined;
      ticketDto.flexBigint8 = object.flexBigint8 ?? undefined;
      ticketDto.flexBigint9 = object.flexBigint9 ?? undefined;
      ticketDto.orderId = object.orderId ?? undefined;
      ticketDto.ticketDefRelId = object.ticketDefRelId ?? undefined;
      ticketDto.ticketId = object.ticketId ?? undefined;
      ticketDto.ticketTypeId = object.ticketTypeId ?? undefined;
    }

    return ticketDto;
  }
}
