class Ticket {
  createdBy?: string;
  createdAt?: Date;
  updatedAt?: Date;
  updatedBy?: string;
  flexBoolean0?: boolean;
  flexBoolean1?: boolean;
  flexBoolean2?: boolean;
  flexBoolean3?: boolean;
  flexBoolean4?: boolean;
  flexBoolean5?: boolean;
  flexBoolean6?: boolean;
  flexBoolean7?: boolean;
  flexBoolean8?: boolean;
  flexBoolean9?: boolean;
  flexFloat0?: number;
  flexFloat1?: number;
  flexFloat2?: number;
  flexFloat3?: number;
  flexFloat4?: number;
  flexFloat5?: number;
  flexFloat6?: number;
  flexFloat7?: number;
  flexFloat8?: number;
  flexFloat9?: number;
  flexInt0?: number;
  flexInt1?: number;
  flexInt2?: number;
  flexInt3?: number;
  flexInt4?: number;
  flexInt5?: number;
  flexInt6?: number;
  flexInt7?: number;
  flexInt8?: number;
  flexInt9?: number;
  flexString0?: string;
  flexString1?: string;
  flexString2?: string;
  flexString3?: string;
  flexString4?: string;
  flexString5?: string;
  flexString6?: string;
  flexString7?: string;
  flexString8?: string;
  flexString9?: string;
  flexString10?: string;
  flexString11?: string;
  flexString12?: string;
  flexString13?: string;
  flexString14?: string;
  flexString15?: string;
  flexString16?: string;
  flexString17?: string;
  flexString18?: string;
  flexString19?: string;
  flexString20?: string;
  flexBigint0?: number;
  flexBigint1?: number;
  flexBigint2?: number;
  flexBigint3?: number;
  flexBigint4?: number;
  flexBigint5?: number;
  flexBigint6?: number;
  flexBigint7?: number;
  flexBigint8?: number;
  flexBigint9?: number;
  orderId?: number;
  ticketDefRelId?: number;
  ticketId?: number;
  ticketTypeId?: number;

  static fromObject(object: any): Ticket {
    const ticket: Ticket = {};

    if (object) {
      ticket.createdBy = object.createdBy ?? undefined;
      ticket.createdAt = object.createdAt
        ? new Date(object.createdAt)
        : undefined;
      ticket.updatedAt = object.updatedAt
        ? new Date(object.updatedAt)
        : undefined;
      ticket.updatedBy = object.updatedBy ?? undefined;
      ticket.flexBoolean0 = object.flexBoolean0 ?? undefined;
      ticket.flexBoolean1 = object.flexBoolean1 ?? undefined;
      ticket.flexBoolean2 = object.flexBoolean2 ?? undefined;
      ticket.flexBoolean3 = object.flexBoolean3 ?? undefined;
      ticket.flexBoolean4 = object.flexBoolean4 ?? undefined;
      ticket.flexBoolean5 = object.flexBoolean5 ?? undefined;
      ticket.flexBoolean6 = object.flexBoolean6 ?? undefined;
      ticket.flexBoolean7 = object.flexBoolean7 ?? undefined;
      ticket.flexBoolean8 = object.flexBoolean8 ?? undefined;
      ticket.flexBoolean9 = object.flexBoolean9 ?? undefined;
      ticket.flexFloat0 = object.flexFloat0 ?? undefined;
      ticket.flexFloat1 = object.flexFloat1 ?? undefined;
      ticket.flexFloat2 = object.flexFloat2 ?? undefined;
      ticket.flexFloat3 = object.flexFloat3 ?? undefined;
      ticket.flexFloat4 = object.flexFloat4 ?? undefined;
      ticket.flexFloat5 = object.flexFloat5 ?? undefined;
      ticket.flexFloat6 = object.flexFloat6 ?? undefined;
      ticket.flexFloat7 = object.flexFloat7 ?? undefined;
      ticket.flexFloat8 = object.flexFloat8 ?? undefined;
      ticket.flexFloat9 = object.flexFloat9 ?? undefined;
      ticket.flexInt0 = object.flexInt0 ?? undefined;
      ticket.flexInt1 = object.flexInt1 ?? undefined;
      ticket.flexInt2 = object.flexInt2 ?? undefined;
      ticket.flexInt3 = object.flexInt3 ?? undefined;
      ticket.flexInt4 = object.flexInt4 ?? undefined;
      ticket.flexInt5 = object.flexInt5 ?? undefined;
      ticket.flexInt6 = object.flexInt6 ?? undefined;
      ticket.flexInt7 = object.flexInt7 ?? undefined;
      ticket.flexInt8 = object.flexInt8 ?? undefined;
      ticket.flexInt9 = object.flexInt9 ?? undefined;
      ticket.flexString0 = object.flexString0 ?? undefined;
      ticket.flexString1 = object.flexString1 ?? undefined;
      ticket.flexString2 = object.flexString2 ?? undefined;
      ticket.flexString3 = object.flexString3 ?? undefined;
      ticket.flexString4 = object.flexString4 ?? undefined;
      ticket.flexString5 = object.flexString5 ?? undefined;
      ticket.flexString6 = object.flexString6 ?? undefined;
      ticket.flexString7 = object.flexString7 ?? undefined;
      ticket.flexString8 = object.flexString8 ?? undefined;
      ticket.flexString9 = object.flexString9 ?? undefined;
      ticket.flexString10 = object.flexString10 ?? undefined;
      ticket.flexString11 = object.flexString11 ?? undefined;
      ticket.flexString12 = object.flexString12 ?? undefined;
      ticket.flexString13 = object.flexString13 ?? undefined;
      ticket.flexString14 = object.flexString14 ?? undefined;
      ticket.flexString15 = object.flexString15 ?? undefined;
      ticket.flexString16 = object.flexString16 ?? undefined;
      ticket.flexString17 = object.flexString17 ?? undefined;
      ticket.flexString18 = object.flexString18 ?? undefined;
      ticket.flexString19 = object.flexString19 ?? undefined;
      ticket.flexString20 = object.flexString20 ?? undefined;
      ticket.flexBigint0 = object.flexBigint0 ?? undefined;
      ticket.flexBigint1 = object.flexBigint1 ?? undefined;
      ticket.flexBigint2 = object.flexBigint2 ?? undefined;
      ticket.flexBigint3 = object.flexBigint3 ?? undefined;
      ticket.flexBigint4 = object.flexBigint4 ?? undefined;
      ticket.flexBigint5 = object.flexBigint5 ?? undefined;
      ticket.flexBigint6 = object.flexBigint6 ?? undefined;
      ticket.flexBigint7 = object.flexBigint7 ?? undefined;
      ticket.flexBigint8 = object.flexBigint8 ?? undefined;
      ticket.flexBigint9 = object.flexBigint9 ?? undefined;
      ticket.orderId = object.orderId ?? undefined;
      ticket.ticketDefRelId = object.ticketDefRelId ?? undefined;
      ticket.ticketId = object.ticketId ?? undefined;
      ticket.ticketTypeId = object.ticketTypeId ?? undefined;
    }

    return ticket;
  }
}
